# Custom Secret Scanning Patterns

# This file can be used to define custom patterns for secret scanning
# GitHub will automatically scan for default secret patterns

# Example custom patterns (uncomment and modify as needed):
# - pattern: '[a-zA-Z0-9]{32}'
#   description: "Custom API Key Pattern"
#   secret_type: "custom_api_key"

# For this repository, we rely on GitHub's default secret scanning patterns
# which include:
# - API keys from major providers (AWS, Google, Azure, etc.)
# - OAuth tokens
# - Private SSH keys
# - Database connection strings
# - And many more

# Enable push protection to prevent secrets from being committed
# This is configured in repository settings under:
# Settings > Code security and analysis > Secret scanning
