# Custom Secret Scanning Configuration

# This file defines additional patterns for GitHub Secret Scanning
# specific to the DailyAccomplishments project integrations

# Note: GitHub automatically scans for common secret patterns (AWS keys, tokens, etc.)
# This file adds patterns specific to services used in this project

# Custom patterns for project-specific integrations:
# - HubSpot access tokens (typically 40 char alphanumeric)
# - Aloware API keys
# - Monday.com API tokens
# - Slack bot tokens (xoxb- prefix)
# - Slack user tokens (xoxp- prefix)

# For actual configuration, these patterns would be defined in:
# Repository Settings > Code security and analysis > Secret scanning
# Under "Custom patterns" section

# Recommended custom patterns to add via GitHub UI:

# 1. Slack Bot Token Pattern:
#    Pattern: xoxb-[0-9]{11,13}-[0-9]{11,13}-[a-zA-Z0-9]{24}
#    Secret Type: slack_bot_token

# 2. Slack User Token Pattern:
#    Pattern: xoxp-[0-9]{11,13}-[0-9]{11,13}-[a-zA-Z0-9]{24}
#    Secret Type: slack_user_token

# 3. Generic API Key Pattern (for custom integrations):
#    Pattern: [a-zA-Z0-9_-]{40,}
#    Secret Type: generic_api_key
#    Note: Use with caution as this may have false positives

# Enable push protection in repository settings to prevent secrets from being committed
# Settings > Code security and analysis > Secret scanning > Push protection

